image: ruby:2.4.2

variables:
 DATABASE_URL: 'mongodb://mongo/user_posts'

before_script:
 - cd reddit

stages:
  - build
  - test
  - review
  - stage
  - production

build_job:
  tags:
    - docker
  image: docker:latest
  variables:
    DOCKER_OPTS: "--insecure-registry=${GITLAB_REGISTRY}"
  stage: build
  services:
    - docker:dind
  script:
    - echo 'Building'
    - echo %GITLAB_REGISTRY%
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t ${GITLAB_REGISTRY}/${CI_PROJECT_PATH}/reddit:${CI_COMMIT_REF_NAME} .
    - docker push ${GITLAB_REGISTRY}/${CI_PROJECT_PATH}/reddit:${CI_COMMIT_REF_NAME}

test_unit_job:
 stage: test
 services:
 - mongo:latest
 script:
 - bundle install
 - ruby simpletest.rb

test_integration_job:
  stage: test
  script:
    - echo 'Testing 2'

deploy_dev_job:
  tags:
    - deploy-server
  stage: review
  script:
   - echo 'Deploy'
  environment:
   name: dev
   url: http://dev.example.com

branch review:
  stage: review
  image: bodymindarts/docker-machine-setup:latest
  script:
    - echo "Deploy to $CI_ENVIRONMENT_SLUG"
    - docker-machine status DM-${CI_COMMIT_REF_NAME} > /dev/null || docker-machine create --driver google --google-disk-size 10 --google-machine-image ${GCP_IMAGE}  --google-machine-type n1-standard-1 --google-zone ${GCP_ZONE} --google-project ${GCP_PROJECT} --engine-insecure-registry ${GITLAB_REGISTRY} reddit-deploy-${CI_COMMIT_REF_NAME}
    - eval $(docker-machine env DM-${CI_COMMIT_REF_NAME})
  environment:
    name: branch/$CI_COMMIT_REF_NAME
    url: http://$CI_ENVIRONMENT_SLUG.example.com
    on_stop: srv_rm
  only:
    - branches
  except:
    - master

srv_rm:
  tags:
    - deploy-server
  stage: review
  script:
    - docker-machine rm -f reddit-deploy-${CI_COMMIT_REF_NAME}
  when: manual
  environment:
    name: branch/$CI_COMMIT_REF_NAME
    url: http://$CI_ENVIRONMENT_SLUG.example.com
    action: stop
  only:
    - branches
  except:
    - master

staging:
  stage: stage
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo 'Deploy'
  environment:
    name: stage
    url: https://beta.example.com

production:
  stage: production
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo 'Deploy'
  environment:
    name: production
    url: https://example.com
