image: ruby:2.4.2

variables:
 DATABASE_URL: 'mongodb://mongo/user_posts'

before_script:
 - cd reddit

stages:
  - build
  - test
  - review
  - stage
  - production

build_job:
  stage: build
  script:
    - echo 'Building'

test_unit_job:
 stage: test
 services:
 - mongo:latest
 script:
 - bundle install
 - ruby simpletest.rb

test_integration_job:
  stage: test
  script:
    - echo 'Testing 2'

deploy_dev_job:
  stage: review
  script:
   - echo 'Deploy'
  environment:
   name: dev
   url: http://dev.example.com

branch review:
  stage: review
  image: docker:latest
  script:
    - echo "Deploy to $CI_ENVIRONMENT_SLUG"
    - $ base=https://github.com/docker/machine/releases/download/v0.14.0 && curl -L $base/docker-machine-$(uname -s)-$(uname -m) >/tmp/docker-machine && sudo install /tmp/docker-machine /usr/local/bin/docker-machine
    - docker-machine status
  environment:
    name: branch/$CI_COMMIT_REF_NAME
    url: http://$CI_ENVIRONMENT_SLUG.example.com
  only:
    - branches
  except:
    - master

staging:
  stage: stage
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo 'Deploy'
  environment:
    name: stage
    url: https://beta.example.com

production:
  stage: production
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo 'Deploy'
  environment:
    name: production
    url: https://example.com
