dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-02/run.sh |
  bash
notifications:
  slack:
    secure: LwbLLO/Al2vm+evF9x45NX/WssCm5Ar6YyZtAwAJkNgAuW6ddn2vcPLN4n/2mH7+xhekkE2sQSjGkHHh9hxC4hN9OurGTBa4Q9gbYIHYTapAOoI6uYGmygAj9FxiREURAwuNueYJhaBAAZNvJk22rz2uRyZsKEV6TeUb63QlSSSTI6ZMEsvaUpvm/Y5dufN5JQ96fSjaLX7qKVy9ied4jWNXUJ6/IEo30J8HjX5Wh/grmFSfJl6W2BQV4PTDyChezeweQq0aquLG2IhtnZxtBZK/LTJ7GBSciKfiHgGx/vurLTbfrOTOsIFc6Gxlhrdn2Onwc8O1Kbp5mMCrIeJb/vhVOwLlVj0Rt9xIqrzvHF8eyYRJcg5YtYJLvISZ6vPXlWIY18ymZYl15drlZBVEZRXk1yyqg+3d0EljHfheMbMRhyNYYKDjyoBTCPDHVhkFZRI0OlOL5iF8XwDc6aeLC4JNwZHOD4wEtnZfplGOh3qXhNpzG+vpMl0QZDBJyT3kP2EfbhUI+vtcocr9NVF6+iiSHbGVj+MX2GTV44tiFzX2JGYtt1v1wdF0dCLshVWViaEKB76Rg3kG9WrYdGRGFD7r/2wlWJoxsO2wJSRRb4Z1TIWg9o1dH+QCwTpzvZXbJiua4ivdESkTHxuXQWdQseulmjch7cvD/z7K5JWW1KE=
