---
- name: Deploy docker
  become: true
  hosts: docker-host
  tags: deploy-docker
  tasks:
  - name:    Install prerequisites
    apt:     name={{item}} update_cache=yes
    with_items:
     - apt-transport-https
     - ca-certificates
     - curl
     - software-properties-common
     - python-pip
     - python-dev
     - build-essential
  - name: install docker-py
    pip:
      name: docker-py
  - name:    Add Docker GPG key
    apt_key: url=https://download.docker.com/linux/debian/gpg
  - name:    Add Docker APT repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/debian {{ansible_distribution_release}} stable
  - name:    Install Docker
    apt:     name=docker-ce
