version: '3.3'
services:
  alertmanager:
    image: ${USER_NAME}/alertmanager
    command:
      - '--config.file=/etc/alertmanager/config.yml'
    ports:
      - 9093:9093
    networks:
      - x-back
  cadvisor:
    image: google/cadvisor:v0.29.0
    volumes:
      - '/:/rootfs:ro'
      - '/var/run:/var/run:rw'
      - '/sys:/sys:ro'
      - '/var/lib/docker/:/var/lib/docker:ro'
    ports:
      - '8080:8080'
    networks:
      - x-back
  grafana:
    image: grafana/grafana:5.0.0
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=secret
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    networks:
      - x-back
  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      - x-back
  mongodb-exporter:
    image: ${USER_NAME}/mongodb_exporter
    environment:
      - MONGODB_URL=mongodb://post_db:27017
    networks:
      - x-back
  blackbox:
    image: prom/blackbox-exporter:v0.12.0
    ports:
      - 9115:9115/tcp
    networks:
      - x-front
  prometheus:
    image: ${USER_NAME}/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
    networks:
      - x-back
      - x-front
      - reddit-loopback
volumes:
  post_db:
  prometheus_data:
  pwd:
  grafana_data:

networks:
  x-back:
    external:
      name: docker_reddit-back
  x-front:
    external:
      name: docker_reddit-front
  reddit-loopback:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 192.168.10.0/30
